name: Integration

on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
        
      - name: Version Check
        run: python --version
      
      - name: Install Poetry
        run: pip3 install poetry
      - name: Configure Poetry
        run: poetry config virtualenvs.create false
      - name: Install Dependencies
        run: poetry install
      
      - name: Lint Sources
        run: inv lint
      - name: Lint Tests
        run: inv lint -t
      - name: Run Tests
        run: pytest
